### PR TITLE
Fix and isolate message receipts

### LINKED ISSUE #115: Rate limiting on too many receipts
We get rate limited since we are sending to many receipts back. 

Atm, this is done in the UI component. We should move it out of there.

### PR DESCRIPTION
**Pull request by Sup3Legacy**
This PR should both :

- Fix #115. This issue originated in a small bug causing the client to repeatedly send empty `ReceiptMessage`s.
- Isolate the handling of these receipts. They take the form of `ReceiptEvent`s that can be created anywhere in the client and they are handled in a separate structure, stored in a set (idea from @boxdot). At regular interval (default 1 per s.; this rate can safely be increased), an event, if any, is sent. 

Technical clarification : the events are sent grouped by `Uuid` and whether they are `Delivered` or `Read`, so the number of waiting events cannot exceed `2 * (number of active conversations)`.

Shortcomings : 

- This handler does not get saved in the database. This means that closing the client while some receipt events are still waiting to get sent will result in them never getting sent at all.

### CODE REVIEW

File: src/app.rs [hunk 1]
```diff
@@ -47,6 +47,138 @@ pub struct App {
...
+            time_since_update: 0u64,
+        }
+    }
+
+    pub fn add_receipt_event(&mut self, event: ReceiptEvent) {
+        // Add a new set in the case no receipt had been handled for this contact
+        // over the current session
+        self.receipt_set
+            .entry(event.uuid)
+            .or_insert_with(ReceiptQueues::new);
```
Comment (boxdot) [inline src/app.rs:72]: This method returns `&mut Value`, so you could store in a variable and do the modification from line 74. This would make the second lookup obsolte.

File: src/app.rs [hunk 2]
```diff
@@ -47,6 +47,138 @@ pub struct App {
...
+
+    pub fn step(&mut self, signal_manager: &dyn SignalManager) -> bool {
+        if !self.do_tick() {
+            return false;
+        }
+        if self.receipt_set.is_empty() {
+            return false;
+        }
+        let uuid = *self.receipt_set.keys().next().unwrap();
+        let mut queue = self.receipt_set.remove(&uuid).unwrap();
```
Comment (boxdot) [inline src/app.rs:94]: You can use `.remove_entry()` to get id and queue at the same time. I think however, it is better to use the `.entry` API to get an entry, and if it is not vacant, to do the logic below. And in-case, its value, the queue, is empty, to remove it.

File: src/app.rs [hunk 3]
```diff
@@ -47,6 +47,138 @@ pub struct App {
...
+    pub fn new() -> Self {
+        Self {
+            received_msg: HashSet::new(),
+            read_msg: HashSet::new(),
+        }
+    }
+
+    pub fn add_received(&mut self, timestamp: u64) {
+        if !self.received_msg.insert(timestamp) {
+            log::info!("Somehow got duplicate Received receipt @ {}", timestamp);
```
Comment (boxdot) [inline src/app.rs:142]: Maybe warn or even error?

File: src/app.rs [hunk 4]
```diff
@@ -47,6 +47,138 @@ pub struct App {
...
+
+    pub fn add(&mut self, timestamp: u64, receipt: Receipt) {
+        match receipt {
+            Receipt::Received => self.add_received(timestamp),
+            Receipt::Read => self.add_read(timestamp),
+            _ => {}
+        }
+    }
+
+    pub fn _add_vec(&mut self, timestamps: Vec<u64>, receipt: Receipt) {
```
Comment (boxdot) [inline src/app.rs:163]: Unused?

File: src/app.rs [hunk 5]
```diff
@@ -47,6 +47,138 @@ pub struct App {
...
+        timestamps.into_iter().for_each(|t| self.add(t, receipt))
+    }
+
+    pub fn get_data(&mut self) -> Option<(Vec<u64>, Receipt)> {
```
Comment (boxdot) [inline src/app.rs:167]: Just asking: shouln't it return received AND read msgs?

File: src/app.rs [hunk 6]
```diff
@@ -998,9 +1135,13 @@ impl App {
...
 
-    pub fn send_receipts(&self, channel: &Channel, timestamps: Vec<u64>, receipt: Receipt) {
-        self.signal_manager
-            .send_receipt(channel, self.user_id, timestamps, receipt)
+    pub fn step_receipts(&mut self) -> anyhow::Result<()> {
+        if self.receipt_handler.step(self.signal_manager.as_ref()) {
+            // No need to save if no receipt was sent
+            self.save()
+        } else {
+            anyhow::Result::Ok(())
```
Comment (boxdot) [inline src/app.rs:1143]: Just `Ok(())` works too

File: src/main.rs [hunk 7]
```diff
@@ -166,6 +168,18 @@ async fn run_single_threaded(relink: bool) -> anyhow::Result<()> {
     let mut last_render_at = Instant::now();
     let is_render_spawned = Arc::new(AtomicBool::new(false));
 
+    let tick_tx = tx.clone();
+    // Tick to trigger receipt sending
+    tokio::spawn(async move {
```
Comment (boxdot) [inline src/main.rs:173]: There is `tokio::time::interval` which gives you a stream of ticks. This one then needs to be joined with `tx`. This is a little bit advanced. Feel free to leave it out!

File: src/ui.rs [hunk 8]
```diff
@@ -257,62 +258,52 @@ fn draw_chat<B: Backend>(f: &mut Frame<B>, app: &mut App, area: Rect) {
...
+    let messages = &mut channel.messages.items[..];
+
+    let _ = messages
+        .iter_mut()
+        .rev()
+        .skip(offset)
+        .for_each(|msg| match msg.receipt {
+            Receipt::Read => (),
+            Receipt::Nothing => (), // Backward-compatibility
+            _ => {
```
Comment (boxdot) [inline src/ui.rs:295]: Maybe it is better to use the name of the variant here? We might add another one, without actually planning to land in this branch.

**Review by boxdot — CHANGES_REQUESTED** [review]
Very nice! Thank you. -- I have some comments.

File: src/app.rs (hunk 5 above)
Comment (Sup3Legacy) [reply src/app.rs:167]: It is possible, however that would require sending two different `ReceiptMessage`, as I understand it. So this is kinda the simple way of doing things

File: src/app.rs (hunk 1 above)
Comment (Sup3Legacy) [reply src/app.rs:72]: Yes ofc, totally missed that one!

File: src/app.rs [hunk 9]
```diff
@@ -90,15 +86,25 @@ impl ReceiptHandler {
...
-        }
+
+        let j = self.receipt_set.entry(uuid);
+        match j {
+            Entry::Occupied(mut e) => {
+                let u = e.get_mut();
+                if let Some((timestamps, receipt)) = u.get_data() {
+                    signal_manager.send_receipt(uuid, timestamps, receipt);
+                    if u.is_empty() {
+                        self.receipt_set.remove_entry(&uuid);
```
Comment (boxdot) [inline src/app.rs:100]: You can call `e.remove_entry()`.

File: src/app.rs [hunk 10]
```diff
@@ -90,15 +86,25 @@ impl ReceiptHandler {
...
+                    }
+                    return true;
+                }
+            }
+            Entry::Vacant(_) => {}
+        };
+        self.receipt_set.remove_entry(&uuid);
```
Comment (boxdot) [inline src/app.rs:107]: There is no need for this call, because this can happen only in the vacant case.

File: src/app.rs (hunk 5 above)
Comment (boxdot) [reply src/app.rs:169]: Thank you for the explanation.

**Review by boxdot — CHANGES_REQUESTED** [review]
Thank you. I just have the last two comments about the entry api, and then we can merge.

File: src/app.rs (hunk 10 above)
Comment (boxdot) [reply src/app.rs:107]: Maybe it even makes sense to move the `false` return value up here, and replace the `return true` in line 105 by `true`.

**Review by boxdot — APPROVED** [review]

**Comment by boxdot** [comment]
Thank you! Awesome work.
